
QUOTES = [
    "Powered By: CIG Sauce"
    "Come on, man, I'm not trying to scam anybody here.",
    "You don't go out and make a living dressed like that in the middle of a weekday.",
    "Is this a — what day is this?",
    "The Dude minds. This will not stand, ya know, this aggression will not stand, man.",
    "The bums will always lose, do you hear me, Lebowski?",
    "I'm just gonna find a cash machine.",
    "OVER THE LINE!",
    "This is not Nam. This is bowling. There are rules.",
    "It's a league game, Smokey.",
    "Dude, tomorrow's already the 10th.",
    "Life does not stop and start at your convenience",
    "You're being very unDude.",
    "Careful, man, there's a beverage here!",
    "That had not occurred to us, Dude.",
    "I could get you a toe by 3 o'clock this afternoon, with nail polish.",
    "I'm staying. I'm finishing my coffee. Enjoying my coffee.",
    "Hey, this is a private residence, man.",
    "Nice marmot.",
    "Is this your homework, Larry?",
    "Do you see what happens, Larry, when you find a stranger in the Alps!",
    "Yes, sir. It is our most modestly priced receptacle.",
    "Sir, this is a mortuary, not a rental house.",
    "Just because we're bereaved doesn't make us saps!",
    "Yeah. Well, you know, sometimes you eat the bear, and, uh...",
    "The Dude abides.",
    "Obviously, you're not a golfer.",
    "Yeah, man, it really tied the room together.",
    "Donny, you're out of your element!",
    "So every time a rug is micturated upon in this fair city, I have to compensate the owner?",
]
