version: 1
disable_existing_loggers: False

filters:
    require_debug_false:
        (): django.utils.log.RequireDebugFalse
    
    require_debug_true:
        (): django.utils.log.RequireDebugTrue
        
formatters:
    standard: 
        format: "%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    django.server:
        (): django.utils.log.ServerFormatter
        format: "[{server_time}] {message}"
        style: "{"

handlers: 
    default: 
        level: DEBUG
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: standard
    
    err_console: 
        level: ERROR
        class: logging.StreamHandler
        stream: ext://sys.stderr
        formatter: standard

    file: 
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/selfservice_ovf/ovf.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8
        
    err_file: 
        level: ERROR
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/selfservice_ovf/ovf_err.log
        maxBytes: 10485760  #10MB
        backupCount: 20
        formatter: standard
        encoding: utf8
    
    django_file: 
        level: DEBUG
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/selfservice_ovf/django.log
        maxBytes: 10485760  #10MB
        backupCount: 8
        formatter: standard
        encoding: utf8
    
    console: 
        level: INFO
        filters: [require_debug_true]
        class: logging.StreamHandler
    
    django.server: 
        level: INFO
        class: logging.StreamHandler
        formatter: django.server
    
    mail_admins: 
        level: ERROR
        filters: [require_debug_false]
        class: django.utils.log.AdminEmailHandler

loggers: 
    __main__: 
        handlers: [default, err_file]
        level: DEBUG
        propagate: False
    
    django: 
        handlers: [console, mail_admins, django_file]
        level: INFO
    
    django.server: 
        handlers: [django.server, django_file]
        level: INFO
        propagate: False

    ovf_deployment:
        handlers: [default, file, err_file]
        level: DEBUG
        propagate: No
       
    accounts:
        handlers: [default, file, err_file]
        level: DEBUG
        propagate: No


root: 
    level: INFO
    handlers: [default]

